import { useRouter } from "next/router";
import { Card, Text, Grid } from "@nextui-org/react";
import Image from "next/image";
import { Input } from "@nextui-org/react";
import { Button } from "@nextui-org/react";
import { FiPower } from "react-icons/fi";
import React, { useContext, useState } from "react";
import Head from "next/head";
import { GlobalService } from "../../../api/services/GlobalService";
const service = new GlobalService();
import toast from 'react-hot-toast';
import { context } from "../../context/providerSpinner";
import logo from "../../../public/logo.png"


export const Login = () => {
  const [values, setValues] = useState({ username: "", password: "" });
  const { setState }: any = useContext(context);
  const router = useRouter();
  const login = (e: any) => {

    document.cookie = "token=true";
    e.preventDefault();
    setState(true);
    service.login(values.username, values.password).subscribe((res: any) => {
      setState(false);
      if (res.DataBeanProperties.ObjectValue.DataBeanProperties.Account) {
        sessionStorage.setItem("user", JSON.stringify(res.DataBeanProperties.ObjectValue.DataBeanProperties.Account.DataBeanProperties))
        document.cookie = "token=true";
        setValues({ username: "", password: "" });
        router.push("/dashboard");
      } else {
        toast.error("usuario o contraseña incorrecto");
      }
    })
  };

  return (
    <div className="login">
      <Head>
        <title>API - AMC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* LOGIN */}

      <Card css={{ width: "800px", backgroundColor: "transparent" }} className="card_login">
        <Grid.Container>
          <Grid sm={12} md={6} lg={6} xl={6} >
            <Card.Body css={{ padding: "40px", display: "flex", justifyContent: "center", alignItems: "center", width: "100%", backgroundColor: 'white' }}>

              <form style={{ textAlign: "center" }} onSubmit={login}>

                <Text h1 size={30} css={{ textGradient: "220.55deg, #FFD439 0%, #FF7A00 90%" }} className="login__titulo" >
                  Iniciar Sesión
                </Text>
                <Input
                  css={{ marginTop: "50px", width: "100%", fontFamily: "Questrial" }}
                  color="warning"
                  size="lg"
                  bordered
                  labelPlaceholder="Usuario"
                  value={values.username}
                  onChange={(e: any) => { setValues({ ...values, username: e.target.value }) }}
                />


                <Input.Password
                  bordered
                  color="warning"
                  css={{ marginTop: "40px", border: "none", width: "100%", fontFamily: "Questrial" }}
                  size="lg"
                  labelPlaceholder="Contraseña"
                  value={values.password}
                  onChange={(e: any) => { setValues({ ...values, password: e.target.value }) }}
                />

                <Button type="submit" shadow size={'lg'} iconRight={<FiPower />} color="warning" css={{ fontFamily: "Questrial", fontSize: "20px", display: "block", marginTop: "40px", width: "100%" }} >
                  Ingresar
                </Button>

              </form>
            </Card.Body>
          </Grid>

          <Grid sm={12} md={6} lg={6} xl={6} css={{ display: "none", position: "relative" }} className="card-login-glass">
            <Card.Body css={{ padding: "0px", display: "flex", justifyContent: "center", alignItems: "center", borderRadius: '0' }} className="login__CardLoginGlass">
              <div className="imagen-login">
                <Image src={logo} />
              </div>
            </Card.Body>
          </Grid>
        </Grid.Container>

      </Card>

    </div>
  );
};
